/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Michael Noguera
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsuarioVista
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        NuevoUsuarioContainer = new javax.swing.JPanel();
        txtRegistrarNombreCompleto = new javax.swing.JTextField();
        txtRegistrarUsuario = new javax.swing.JTextField();
        txtRegistrarPassword = new javax.swing.JTextField();
        txtRegistrarPasswordV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrarContinuar = new javax.swing.JButton();
        btnRegistrarVolver = new javax.swing.JButton();
        InicioSesionContainer = new javax.swing.JPanel();
        txt_inicio_usuario = new javax.swing.JTextField();
        txt_inicio_password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnNuevoUsuario = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        NuevoUsuarioContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Usuario"));
        NuevoUsuarioContainer.setToolTipText("Inicio");
        NuevoUsuarioContainer.setName("nuevoUsuario"); // NOI18N

        txtRegistrarNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarNombreCompletoActionPerformed(evt);
            }
        });

        txtRegistrarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarPasswordActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre de Usuario:");

        jLabel4.setText("Nombre Completo:");

        jLabel6.setText("Constraseña:");

        jLabel7.setText("Verifica Contraseña:");

        btnRegistrarContinuar.setText("Continuar");

        btnRegistrarVolver.setText("Volver");

        javax.swing.GroupLayout NuevoUsuarioContainerLayout = new javax.swing.GroupLayout(NuevoUsuarioContainer);
        NuevoUsuarioContainer.setLayout(NuevoUsuarioContainerLayout);
        NuevoUsuarioContainerLayout.setHorizontalGroup(
            NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NuevoUsuarioContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrarContinuar)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NuevoUsuarioContainerLayout.createSequentialGroup()
                .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevoUsuarioContainerLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(NuevoUsuarioContainerLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4)))
                    .addGroup(NuevoUsuarioContainerLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnRegistrarVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NuevoUsuarioContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)))
                .addGap(36, 36, 36)
                .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRegistrarPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txtRegistrarNombreCompleto)
                    .addComponent(txtRegistrarPasswordV)
                    .addComponent(txtRegistrarUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NuevoUsuarioContainerLayout.setVerticalGroup(
            NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoUsuarioContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistrarNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistrarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistrarPasswordV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(NuevoUsuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarContinuar)
                    .addComponent(btnRegistrarVolver))
                .addGap(35, 35, 35))
        );

        InicioSesionContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio de Sesión"));
        InicioSesionContainer.setToolTipText("Inicio");

        txt_inicio_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inicio_usuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        btnIniciarSesion.setText("Continuar");

        btnNuevoUsuario.setText("Nuevo Usuario");

        javax.swing.GroupLayout InicioSesionContainerLayout = new javax.swing.GroupLayout(InicioSesionContainer);
        InicioSesionContainer.setLayout(InicioSesionContainerLayout);
        InicioSesionContainerLayout.setHorizontalGroup(
            InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioSesionContainerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciarSesion)
                .addGap(29, 29, 29))
            .addGroup(InicioSesionContainerLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_inicio_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_inicio_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        InicioSesionContainerLayout.setVerticalGroup(
            InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioSesionContainerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_inicio_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioSesionContainerLayout.createSequentialGroup()
                        .addGroup(InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_inicio_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioSesionContainerLayout.createSequentialGroup()
                        .addGroup(InicioSesionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoUsuario)
                            .addComponent(btnIniciarSesion))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InicioSesionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NuevoUsuarioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InicioSesionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NuevoUsuarioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        NuevoUsuarioContainer.getAccessibleContext().setAccessibleName("Inicio de Sesion");
        NuevoUsuarioContainer.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_inicio_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inicio_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inicio_usuarioActionPerformed

    private void txtRegistrarNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrarNombreCompletoActionPerformed

    private void txtRegistrarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InicioSesionContainer;
    private javax.swing.JPanel NuevoUsuarioContainer;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JButton btnRegistrarContinuar;
    private javax.swing.JButton btnRegistrarVolver;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtRegistrarNombreCompleto;
    private javax.swing.JTextField txtRegistrarPassword;
    private javax.swing.JTextField txtRegistrarPasswordV;
    private javax.swing.JTextField txtRegistrarUsuario;
    private javax.swing.JTextField txt_inicio_password;
    private javax.swing.JTextField txt_inicio_usuario;
    // End of variables declaration//GEN-END:variables
}
